.\" Manpage for pldm-ver.
.TH man 8 "3 Jul 2025" "1.0" "pldm-ver man page"
.SH NAME
pldm-ver \- Get all version information of PLDM image

.SH SYNOPSIS
.B pldm-ver
Usage: ./pldm-ver <PLDM image file>

.SH DESCRIPTION

pldm-ver is a utility script to fetch all version information of packages inside a PLDM image.

.SH KNOWN ISSUES

This script only supports BF3 for now.
