#!/bin/sh
set -e

case "$1" in
  configure)
    # Unmask the service if it was previously masked.
    # rshim service will be masked after "dpkg -i" or "apt remove" before 2.0.30
    deb-systemd-helper unmask 'rshim.service' >/dev/null || true
    echo "Installation complete. To enable and start the rshim service, run:"
    echo "  systemctl daemon-reload"
    echo "  systemctl enable rshim"
    echo "  systemctl start rshim"
    ;;
esac
